### PR TITLE
Auto detect background changes for Gnome/Cinnamon

### PR DESCRIPTION
**Pull request by dboun**
Hi, I have edited the gnome(&cinnamon) script to auto detect the wallpaper set by the user. Tested only on cinnamon (LM 19.2), but should work on gnome too as nothing is cinnamon-specific.

#### How it works

- Gnome keeps the current wallpaper in the directory ```$HOME/.cache/wallpaper```. There is always only one file there, that doesn't have a file extension and has a long name with random letters. The file is "secretely" a jpeg.
- When we detect a new file there, and it was not because we blurred the background, we copy it to ```$HOME/.cache/wallblur/wallpaper.jpeg``` and use that.
- **Edit:** It can now detect when all windows are minimized and unblur

#### Issues

- Slideshows still don't work, because when we set a blurred image as background, gnome acts like we turned slideshow off. This is not fixable, unless slideshows are implemented as a feature of this script.
- The user should wait 5+ seconds each time he changes the background to change to a new one, because of the issue above. If he changes too fast, the change will not be detected. **Edit:** In commit "Add notifications for the new wallpaper timeout" notifications were added to inform the user when it's ok to change wallpaper again

#### Showcasing usage

Sorry about the quality, turning mkv to gif is hard :P

out2

### CODE REVIEW

**Comment by mut-ex** [comment]
Hi! Great, additions!  Like that it auto-detects the wallpaper changes without needing to be re-started. The only issue is that gnome keeps its cached wallpaper elsewhere (at ~/.cache/gnome-control-center/backgrounds). And seems like even then only the user-added wallpapers are cached there.

**Comment by dboun** [comment]
@turing753 Thank you! If you look at the new commits I think I have fixed everything! I haven't been able to actually test it on gnome, but it should work.

Also switching fastly between wallpapers now happens without issues.

**Comment by dboun** [comment]
In the last commit I changed the readme to prompt users of gnome/cinnamon to add to startup applications instead, because ```.xprofile``` was not working (maybe the scripts there run before gsettings initializes? idk).

It works great now though!

**Comment by mut-ex** [comment]
Great work! Just tested it out on gnome and it is working great! I am going to merge the changes.

**Comment by sokopa** [comment]
Thanks mr books! Amazing work!

**Comment by dboun** [comment]
@sokopa god damn it 😂

**Pull request merged**
